[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/jp/:splat"
  status = 200
  force = true
  conditions = {hostname = "i18-astro-starter-jp.semoneytronic.com"}

[[redirects]]
  from = "/jp/*"
  to = "/:splat"
  status = 200
  force = true
  conditions = {hostname = "i18-astro-starter.semoneytronic.com"}

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"